version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    networks:
      - postgres
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxxkKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local

  cache:
    driver: local

networks:
  postgres:
    driver: bridge